name = "hafiz-farhad-website"
compatibility_date = "2024-01-01"

[env.production]
name = "hafiz-farhad-website"
routes = [
  { pattern = "hafizfarhad.com/*", zone_name = "hafizfarhad.com" },
  { pattern = "www.hafizfarhad.com/*", zone_name = "hafizfarhad.com" }
]

[[env.production.rules]]
type = "Text"
globs = ["**/*.html"]
[env.production.rules.result]
cache = true

[[env.production.rules]]
type = "Text"
globs = ["**/*.css", "**/*.js"]
[env.production.rules.result]
cache = true

[env.production.build]
command = "pnpm build"
cwd = "."
watch_dir = "src"
